version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_DSN=redis://redis/0
    ports:
      - 8080:8080
